### ISSUE TITLE
Add registration spam protection (captcha)

### ISSUE THREAD

**Issue by ErdnussFlipS** [TouchTheBeat/Backend#22]

**Comment by hstolte** [comment]
I read the code in your commit https://github.com/TouchTheBeat/Backend/commit/1a2c3786a261c00c88dec3a85c74957876db706cand and saw that the ``POST USER`` route now requires the additional parameter ``g-recaptcha-response``. I tested it by sending a request like the following to ``POST USER``:

````javascript
{
"username":"" // a non existing username,
"email":"" // a valid, not yet registered email adress,
"password":"" // a hashed password,
"homepage":"" //empty,
"g-recaptcha-response":"" //the value reCAPTCHA generates (a long string)
}
````

The response is the following:

````javascript
{
"data":null,
"error":1245185,
"error_data":["invalid-input-response"],
"error_message":"Google reCAPTCHA failed."
}
````
``1245185`` there stands for ``SIGNIN_USER_NOT_FOUND``, which is irritating because i am actually trying to sign up and not to sign in.

Please review and provide some information on what error codes can occur and when.

**Comment by hstolte** [comment]
It should be possible to reproduce this at https://touchthebeat.github.io/TouchTheBeat/edge/master. 

for chrome:
- open https://touchthebeat.github.io/TouchTheBeat/edge/master
- open the network panel in the developers console (F12)
- reload the page (so that you see the ``GET codes`` response)
- then try to sign up

**Comment by ErdnussFlipS** [comment]
"invalid-input-response": Are you use the same secret as the backend use?

**Comment by ErdnussFlipS** [comment]
Is already defined in apidoc. You have to generate it or go to http://ttb-server.coloreddrums.de/dev/docs/api/index.html

**Comment by hstolte** [comment]
:+1:
